version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    env_file:
      - .env
    container_name: goat_tipg
    hostname: goat_tipg
    command: bash -c "while true; do sleep 1; done"
    volumes:
      - .:/app
